### ISSUE TITLE
Naming could be greatly improved

### ISSUE THREAD

**Issue by julien-devatom** [morpho-dao/morpho-rewards#85]
## Current Behavior

By @MathisGD: The naming of the values returned by the API is not always very clear. I would do a complete revamp, that's worth taking the time IMO. Example in for the rewards:

<img width="518" alt="228257556-2f67b94d-7329-4258-86e2-988d0cb7bb11" src="https://user-images.githubusercontent.com/61523188/228441324-1a7eb2b7-3c71-4871-a89b-b694073084e3.png">

Happy to jump in a call to give some ideas for that :-)

**Comment by julien-devatom** [comment]
Not really easy to refactor since some users are using the API in production. We'll think about that soon.
My suggestion:
- `supply` -> `totalMorphoEmittedSupplySide`
- `supplyRate` -> format the rate with 18 decimals and changes to `supplyRatePerSecond`
- `totalMarketSupply` -> `underlyingSuppliedSnapshot`, and value formatted with decimals

**Comment by MathisGD** [comment]
I think that it is great if "Morpho" appears everywhere where we talk about Morpho rewards

**Comment by julien-devatom** [comment]
@MathisGD This is the final naming adopted: 
![image](https://user-images.githubusercontent.com/61523188/230313747-0d2c0961-3c78-474a-af46-b657b30659f1.png)
I'll ping you once the API will have a new endpoint with this naming (the previous one is going to be deprecated smoothly)

**Comment by MathisGD** [comment]
Perfect !
